### ISSUE TITLE
How do we go about using the Neo4J transformation? There seems to be no argument to specify the type of output, it automatically uses the csv transformation

### ISSUE THREAD

**Issue by aamalik7196** [MGrin/transactions-graph-generator#2]

**Comment by MGrin** [comment]
I'm not sure I understand your question. Are you asking how to get generated graph in neo4j? To do this, firstly generate a graph with `generateGraph.py` script. It will generate a bunch of csv files. Then run scripts/output2neo4j, this will import these csv into neo4j
