### ISSUE TITLE
Mimesis Method Update Issue

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [MGrin/transactions-graph-generator#5]
In the below script,
https://github.com/MGrin/transactions-graph-generator/blob/master/models/Transaction.py

Line 23, between() method doesn't exist anymore in Numbers provider of Mimesis package.

I think integer_number() would be the apporpriate method now.

**Comment by MGrin** [comment]
It took me a lot of time, but fixed. Thank you! :)
